export const ALL_TIERS = ["Start", "Speed", "Super", "Star"];

export const TIER_CONFIG = {
  Start: {
    icon: "🚩",
    min: 0,
    max: 9999,
    bg: "#f1f5f9",
    border: "#cbd5f5",
    color: "#475569",
    range: "0 - 9,999 บาท",
    budget: "1,000 บาท/เดือน",
    requirement: "100 Content/เดือน\n(ปัก 96 + value 4)",
    reward: ["ได้หนังสือ 2 เล่ม ตั้งแต่ครั้งแรก"],
    specialRights: [
      "Ads เพิ่มการมองเห็นให้ฟรี (เจ้าของแบรนด์เลือกคลิปเอง)",
      "Ads GMV Max ทุกตะกร้า",
      "ทำคอนเทนต์ขึ้นชมเพิ่ม Awareness",
      "J affiliate coaching ตรงจากแบรนด์ให้ฟรี",
    ],
    discount: null,
  },
  Speed: {
    icon: "⚡",
    min: 10000,
    max: 49999,
    bg: "#e0f2fe",
    border: "#7dd3fc",
    color: "#0284c7",
    range: "10,000 - 49,999 บาท",
    budget: "1,000 บาท/เดือน",
    requirement: "60 Content/เดือน\n(ปัก 56 + value 4)",
    reward: ["มีหนังสือเพิ่มให้จากเดิมอีก 2 เล่ม"],
    specialRights: [
      "Ads เพิ่มการมองเห็นให้ฟรี (เจ้าของแบรนด์เลือกคลิปเอง)",
      "Ads GMV Max ทุกตะกร้า",
      "ทำคอนเทนต์ขึ้นชมเพิ่ม Awareness",
      "J affiliate coaching ตรงจากแบรนด์ให้ฟรี",
    ],
    discount: null,
  },
  Super: {
    icon: "🚀",
    min: 50000,
    max: 199999,
    bg: "#fef9c3",
    border: "#fde047",
    color: "#ca8a04",
    range: "50,000 - 199,999 บาท",
    budget: "1,000 บาท/เดือน",
    requirement: "40 Content/เดือน\n(ปัก 36 + value 4)",
    reward: [
      "รับโบนัสเพิ่ม 1% ของยอดขาย (สูงสุด 2,000 บาท)",
      "มีหนังสือเพิ่มให้จากเดิมอีก 4 เล่ม",
    ],
    specialRights: [
      "ส่วนลดต่าง ๆ (คูปอง/แฟลชเซลล์ เฉพาะบุคคล)",
      "Ads เพิ่มการมองเห็นให้ฟรี (เจ้าของแบรนด์เลือกคลิปเอง)",
      "Ads GMV Max ทุกตะกร้า",
      "ทำคอนเทนต์ขึ้นชมเพิ่ม Awareness",
      "J affiliate coaching ตรงจากแบรนด์ให้ฟรี",
    ],
    discount: "ส่วนลดต่าง ๆ (คูปอง/แฟลชเซลล์ เฉพาะบุคคล)",
  },
  Star: {
    icon: "⭐",
    min: 200000,
    max: 9999999,
    bg: "#ede9fe",
    border: "#c4b5fd",
    color: "#7c3aed",
    range: "200,000+ บาท",
    budget: "1,000 บาท/เดือน",
    requirement: "40 Content/เดือน\n(ปัก 36 + value 4)",
    reward: [
      "ยอดขายทุก ๆ 200K บาท รับฟรี แหวนทอง 1 วง (มูลค่า 3,000 บาท)",
      "ยอดขาย 1 ล้านบาท/เดือน แจกเซ็ต iPad + Apple Pencil",
    ],
    specialRights: [
      "ส่วนลดต่าง ๆ (คูปอง/แฟลชเซลล์ เฉพาะบุคคล)",
      "Ads เพิ่มการมองเห็นให้ฟรี (เจ้าของแบรนด์เลือกคลิปเอง)",
      "Ads GMV Max ทุกตะกร้า",
      "ทำคอนเทนต์ขึ้นชมเพิ่ม Awareness",
      "J affiliate coaching ตรงจากแบรนด์ให้ฟรี",
    ],
    discount: "ส่วนลดต่าง ๆ (คูปอง/แฟลชเซลล์ เฉพาะบุคคล)",
  },
};
